name = input("please enter your name: ")
print("Your name is ",name)
print("Upper Case: ",name.upper())
print("Lower case: ",name.lower())
print("Swap case: ", name.swapcase())
print("Title case: ",name.title())
print("Length of name:",len(name))
print("The letter 'o' occurs:",name.count('o'))
print("The position of 'o' is:",name.find('o'))

